In [1]:
import pandas as pd

In [18]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [4]:
# import numpy
import numpy as np

In [5]:
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [6]:
# length of the array
len(language_score)

1000

In [7]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [8]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size=1000)

In [9]:
# min value inclusive and high value exclusive
print(min(int_language_score))
print(max(int_language_score))

1
99

In [10]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,39
1,female,group C,some college,standard,completed,69,90,88,58
2,female,group B,master's degree,standard,none,90,95,93,7
3,male,group A,associate's degree,free/reduced,none,47,57,44,92
4,male,group C,some college,standard,none,76,78,75,91
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,34
996,male,group C,high school,free/reduced,none,62,55,55,37
997,female,group C,high school,free/reduced,completed,59,71,65,72
998,female,group D,some college,standard,completed,68,78,77,79
999,female,group D,some college,free/reduced,none,77,86,86,5

In [11]:
# create random float numbers between 1 and 100
np.random.uniform(1, 100, size=1000)

array([ 4.86459736, 77.24015199, 40.16118419, 61.95260972, 79.46499473,
       56.76971786, 20.80271264, 14.97939698, 69.50446544, 41.95132401,
       94.00953971, 17.49010661, 44.08837211, 42.31437563, 47.43149719,
       65.27628309, 76.77872377, 47.89161556, 71.2312646 , 81.14221338,
       96.91075322, 26.51138307,  1.99731429, 45.16928872, 45.35349148,
       77.54929439, 97.62761713, 43.78409271, 17.40379358, 20.13489659,
       77.18697501,  2.63464851, 95.4546391 , 62.46169641, 13.98847124,
        7.3428277 , 33.54759602, 72.71464994, 57.01731816, 96.93216489,
       91.5773272 , 62.26684526, 53.6807132 , 42.65217075, 11.12031871,
       91.02465395, 61.45348498, 63.27823135, 91.72181952, 12.06903644,
       31.85561743, 94.18143596, 50.05572345, 55.67527298, 11.34522733,
       78.86497619, 50.14333048, 71.30713411,  6.99151831, 37.95681453,
       78.6068085 , 34.62935382, 55.01054884, 97.21800341, 31.94223602,
       94.22242898, 56.64769309, 53.98895257, 72.14260431, 43.20094643,
       11.38198665, 98.79666597,  8.78017224, 39.18025304, 36.1215693 ,
       40.53932293, 27.31626391, 66.02743048, 57.81164925, 41.35682263,
       38.74920185, 38.36502948, 29.19429534, 93.823669  , 57.15254517,
       13.26998732, 80.65791834, 19.6809658 , 75.89847354, 36.15449971,
        3.76606211, 46.12084778, 60.47507017, 18.64423337, 64.00618895,
       51.89851056, 44.69953503, 95.26735585, 62.763013  , 38.70016099,
        6.18822229,  9.68078335,  2.69096662, 26.77003274, 41.8437844 ,
       81.99087292, 32.70592701, 33.51496037, 17.47697988, 46.26802115,
       35.51369363, 36.12886281, 14.81131574, 88.29423235, 31.87581394,
       44.21126616, 36.0692982 , 58.86677004, 64.48796758, 93.15131159,
       13.34833559, 27.54784125, 49.03302905, 12.31888117, 26.27402969,
       23.5292946 , 36.54163073, 66.72888487, 82.67553349, 25.19103439,
        8.46681079, 56.80964104, 83.22503812, 87.00904339, 68.77500102,
       28.74676088,  8.05426484, 26.07774588, 79.82281585, 40.65721261,
       72.27012884, 90.75837851, 79.84777809, 33.86450416, 24.11555078,
       94.59438099, 12.41285521, 65.706562  , 91.99996069, 59.70651799,
       17.75829767, 21.31232061, 11.13219699, 74.29336458, 96.43609347,
       60.5744799 , 74.72983873, 33.63065669, 87.49149916, 16.84921405,
       32.01634038, 11.32294324, 67.38725148,  1.64140137, 28.09251268,
       41.5794724 , 45.41237549, 25.40378409, 82.42685269, 25.15560462,
       29.89867835, 95.72551724, 79.61776261, 34.31261247, 12.51594685,
       87.68496773, 79.73644108, 16.27888777,  9.45213646, 66.33068508,
       22.87444353, 36.6825975 , 85.57274166, 69.43221696, 28.82151146,
       12.00727401, 71.14039924, 94.06065029, 21.84348035, 86.53906777,
       43.11265643, 98.25320546,  9.34527564, 44.33455771, 84.79448664,
        8.53510218, 21.70916446, 39.27482052, 14.10451231, 11.40045261,
       74.01417943, 23.4112216 , 97.9546256 ,  5.81646187, 69.79433111,
       85.68279416, 62.10429375, 72.4976372 , 27.86519991, 21.38744773,
       79.8488095 , 45.9863003 , 57.91478931, 27.45029424, 88.93753677,
       78.49408623,  1.22079845, 32.53297311, 21.39465991, 90.17374553,
       45.74375579, 87.7015792 , 29.58197751, 57.40427752, 92.8048562 ,
       90.87776606, 81.38797873,  9.05933099, 35.01344572, 92.70639832,
       44.71915147, 68.35016225, 69.48687683, 75.99338359, 64.33197332,
       51.02314428, 51.34329466, 11.98384179, 59.09493148, 32.69475419,
        1.1863346 , 81.94659024,  5.86903368, 73.98508245, 72.83960674,
       22.82521779, 32.74112981, 55.87193751, 78.27527645, 25.01483186,
       67.99034543, 27.99097348, 76.9509236 , 17.98000596, 15.94024385,
       31.04321663, 98.68443705, 58.44429934, 41.34522079, 61.1398674 ,
       97.4759292 , 27.8531272 , 27.5756868 ,  6.2923044 , 66.51944338,
       59.26015689, 72.29511043,  8.6747466 , 43.1061211 ,  6.7559367 ,
       81.84167908,  7.83523303, 26.69260648, 82.28397055, 62.30592217,
       16.80290702,  7.75268485, 66.52667596, 32.80210882, 20.74440978,
       34.46538496, 53.24123682, 49.83415245, 88.46409618, 85.30062213,
       69.34400279, 11.49276095, 65.19377387, 60.13376584, 36.60479846,
       82.03945899, 32.99152649, 33.41060607,  4.67891756, 91.2485605 ,
       86.8175813 , 18.58471673, 29.93207656, 79.52998609, 55.61422884,
       77.28913418,  1.64485267, 33.57603432, 23.93215652, 30.82058209,
       72.89819734, 27.06978161, 54.50817878, 96.67112898, 12.89128709,
        2.24068546, 40.30797881, 44.71527549,  5.43387557, 41.06191282,
       45.43143037,  9.32409628, 62.28857444, 55.945486  , 29.72419612,
       53.34033586, 91.19108701, 69.98953121, 56.16499813, 16.73315063,
        8.21175093, 48.13793259, 41.43080743, 87.60295563, 25.11651428,
       72.49192938, 47.82274636, 28.75008821,  1.74174   , 17.0822876 ,
       47.00984302, 83.46509131, 87.83877747, 90.60719412, 58.51155653,
       81.0358917 , 57.00728786, 93.56488895, 77.92066786, 63.63797708,
       76.00417233, 59.45767334, 17.800173  , 70.35587316, 51.43384913,
       20.51625012, 58.0584133 , 59.26141363, 24.13280324, 73.86523136,
       41.71906013, 96.71372599, 24.94565333, 91.889511  , 23.86873517,
       18.1726428 , 16.47970046, 39.421894  , 58.76438697, 72.61510027,
        8.98083492, 25.80366301, 97.36259832, 72.57656615, 45.83440555,
       89.38800842, 59.16779936, 23.42374547, 58.33513825, 69.28630841,
       95.57837044,  8.91443167, 92.81603913, 35.4398983 , 99.48818733,
       18.21444059, 80.40044115, 97.97001518, 63.86516407, 89.65164535,
       58.85709908, 72.57035341, 91.02342981,  9.20396181, 67.08603164,
       10.76327224, 23.63117924, 22.58536261, 52.71905533, 35.96959684,
       11.94289815, 96.42803745, 71.88425745, 17.59117127, 54.56004342,
       27.35584176, 64.76987258, 98.27467773, 76.25515271, 36.79036245,
        9.178586  ,  8.55514769, 32.71583456, 41.84545277, 62.89856987,
       32.30409699, 48.03212534, 36.5526829 , 43.24139048, 48.25382293,
       10.6048604 , 80.1148836 , 13.79056136, 48.89954067, 24.1285205 ,
       38.48885781, 34.40770151, 90.15270148, 28.96035439,  3.3197049 ,
       52.01646124, 72.11963487, 54.37798497, 26.67612367, 47.29428613,
       12.01149707, 18.23017431, 71.28319034, 41.39065007, 16.87010164,
       68.33421947, 65.39461307, 16.22718653, 44.22044075,  3.78900289,
       20.13074071, 96.2149695 , 70.09403993, 37.31476924, 11.17296154,
       33.78666606, 42.9557863 , 77.14302323, 21.93271282, 79.95804941,
       86.47651218, 58.90424738, 14.9114662 , 24.35981459, 61.10762642,
       96.60600181, 32.51596002, 83.72745881, 10.16426773, 31.5916095 ,
       77.57951292, 76.54480932,  4.00812684, 29.17995173, 36.40909275,
       29.78127737, 56.37174346, 23.4181488 , 24.02636614, 63.36945674,
       51.89841348, 70.76717812, 72.51593053,  5.53663142, 48.47936556,
       29.11884143, 40.75258719,  5.24883928, 48.77582859, 33.46882653,
       84.2747404 ,  8.98198912, 10.51994084, 79.17767726, 39.80699381,
       76.06436529, 55.38815609, 45.09853732, 68.44153694, 81.09196922,
       11.11987899, 71.54155139, 71.52973598, 21.44239682, 80.6144065 ,
        9.07617749, 66.97470376, 80.58178687, 94.55198721, 22.95268426,
       78.40593012, 81.31064264, 19.82877579, 27.0134549 , 39.64694791,
       35.72773919, 85.98434613, 23.47485056, 98.3287235 , 19.78581389,
       84.24376633, 17.28513412, 26.48427722,  1.13446584, 36.38962766,
        1.1635951 ,  7.10393804, 82.86511374, 41.96150566, 15.26122716,
       51.9183273 , 80.88588583, 57.97846861, 92.42593922, 85.9773276 ,
       37.73074636, 67.35598865, 48.04033985,  2.90121954, 31.37986365,
       73.07678442, 23.62011418, 78.79888351, 48.22376578, 65.4512508 ,
       58.91285699, 13.18951997, 50.53113842, 14.05298329, 41.02840493,
       22.70986118, 49.79927697, 70.53448539,  9.17461206, 94.0908279 ,
       93.18155983,  8.91707826, 18.39030116, 83.08207041, 10.28912444,
       89.2692857 , 17.3011853 , 92.01376596, 10.29917429, 11.70239245,
       32.56115292, 41.46086262, 75.3652937 , 93.48516251, 14.1682053 ,
        2.74818455, 71.96061162, 18.60419476, 13.82476143, 57.55968826,
       21.63568521,  9.80329613, 66.28032685, 82.47676411, 39.28370624,
       87.5192031 , 98.96677829, 22.74010294, 95.14247826, 55.9805005 ,
       46.49445507,  5.82986467, 74.42817582,  1.32247787, 13.00224086,
       65.00200679, 35.40292392, 28.16609297, 77.10795371,  6.51977306,
       30.55030347, 16.65969272,  9.09953283, 88.79890075, 34.45703577,
       35.17351588, 66.14060596, 63.45522454, 73.69269642, 28.25379105,
       60.5214621 , 11.16289517, 18.63485659, 31.62256257, 98.12715064,
       76.63357072, 67.11185286, 49.19507827,  1.79828703, 83.33414966,
       49.82019037, 20.59227471, 51.47225455, 54.74923814, 81.33721048,
       55.0892821 , 73.88885051, 90.55104883, 48.3160008 , 55.26208303,
       13.15675583, 21.95294003, 77.28414598, 95.75899335, 59.27698395,
        3.74460829, 54.90121045, 84.26659966, 75.80326097, 89.53439079,
       53.45370845, 87.88704447, 50.01210225,  5.73038169, 13.42644793,
       63.03538875, 27.79097727,  5.61557239, 49.49105384, 13.01191523,
       69.23368328, 45.2123528 , 57.12326294, 74.20051816, 34.06256963,
       91.99465038, 72.45889986, 41.82951813, 45.31321205, 99.51682796,
       51.96247292, 22.78250269, 36.03327504, 57.95233801, 20.09214185,
       89.52328161, 28.94024089, 43.54256545, 40.78740624, 19.48889721,
       33.46743648, 24.20460369, 82.28394417, 15.87128431, 14.57828304,
       63.88909034, 23.09656147, 17.44991471, 34.67404268, 18.62405233,
       91.84771037, 16.08757953, 87.66290704, 82.4202535 ,  1.11003327,
       38.29169484,  4.94702153,  7.9187489 , 18.38810135, 77.60300717,
       11.00659164, 21.96016676, 39.36788246, 75.4809855 , 32.87823017,
       78.15677099, 84.18390869,  1.57399022, 57.16720338, 93.86808961,
       51.35886913,  9.45272653, 50.18951443, 68.7092061 , 17.96344582,
       74.01814636, 84.733037  , 79.1163038 , 94.05284829, 48.9762435 ,
       90.11575197, 92.57971281, 88.29585748, 34.00219982, 79.55546406,
       91.69557746, 17.73378408, 45.93236995, 67.47185682, 88.13517665,
       70.60877575, 12.50184468, 72.59630675, 52.36043689, 78.1063452 ,
       93.6034233 , 70.55393709,  5.7401214 , 59.71371677, 65.75519139,
       71.47269149, 40.29406536, 86.2692055 , 82.9469425 , 70.40819259,
       24.14602379, 59.31917598, 76.00388504,  8.15512627, 86.27545366,
       98.81875066, 20.76720642, 22.8903709 , 78.93185478, 89.0251364 ,
       32.61603216, 69.83082975, 53.50165949, 80.68014886, 53.07698249,
       24.05496182, 46.84738504, 90.24920057, 83.60861786, 64.09994888,
       41.47628519, 91.05139955, 44.64311877, 28.29562101, 61.86442513,
       62.85860196, 97.04175061, 81.13503173, 31.18713196, 66.85534806,
       89.6099592 , 18.15468692, 21.35068931,  9.52258016, 46.03712418,
       94.93629904, 83.74633654, 69.31176328,  9.60635762, 56.02274371,
       87.51119777, 45.96908175,  1.48007706, 44.20210691, 36.14253857,
       63.45979198, 14.74562933, 78.46846781, 57.93438482,  5.58970014,
       58.12806222, 52.54160281, 68.81620205, 95.9917761 , 10.18349021,
       92.88112105, 84.90275342, 54.28768445, 36.11781934, 61.28689027,
       52.03257   , 17.68009557, 18.87250438, 33.14313539, 82.65088604,
       91.62141198, 88.45699639, 14.21596947, 85.62912727, 59.8770155 ,
       49.40347673, 43.81337851, 27.84832376, 20.01501091, 70.04715395,
       18.63969432, 99.00745707, 14.78678719, 73.96856276, 55.61965229,
       51.20006899, 43.16902918, 21.53765443, 76.7394644 , 62.67959739,
       29.18573154, 83.00580756, 90.59728067, 59.20883272, 71.6277586 ,
       85.17996388, 84.44728139, 50.86859894,  9.06193467, 85.24756576,
       81.13592431, 40.4219179 , 27.24917658, 92.3921618 , 22.65575045,
       29.91462773, 88.64087589, 76.63782498, 86.10590431, 88.04369582,
       40.69283349, 44.67845478, 14.83092532, 23.16888234, 38.48793346,
       14.64996399, 52.50172215, 44.3925466 , 41.55357695, 97.12004047,
       96.09800605, 76.37560876, 20.66647054, 73.98038796, 31.46554502,
       47.36955782, 34.42926529, 94.10503723, 54.8053552 ,  8.08724086,
       87.74010157, 80.05447618,  7.96472886, 98.05898487, 37.74875336,
       48.79232134, 48.7054578 , 86.61611159, 52.22232304, 30.78054837,
       91.89647469, 50.51007985, 31.61808035, 34.94902917, 41.02156049,
       54.4391319 , 83.84147222, 54.52364277, 52.75615577, 53.73378849,
       87.91466189, 34.31175959, 85.14884925,  7.5833346 , 94.06720386,
       28.85531915, 74.00309247, 61.86576372, 58.51832956,  9.33006998,
        8.80246278,  4.85023715, 12.3321708 ,  9.28681056, 93.31609169,
       72.43756202, 99.02234273, 36.49026406, 95.57238018, 28.58987067,
       58.41891954, 75.96749559, 54.97782621, 17.2950121 , 50.49266632,
       36.5939013 , 59.38163046, 45.27286396, 68.8037661 , 94.09154271,
       64.58900443, 33.14639657, 19.54178151, 21.91680412, 63.0713429 ,
       43.79479041,  7.75601282, 95.61473897, 73.96714554,  2.68695469,
       65.38977595, 93.95157679, 11.17711115, 61.83965215, 30.97712956,
       94.8385496 , 82.2740212 , 83.83290212,  8.85560396, 30.6705773 ,
       74.08514979, 24.38136234, 18.40361811, 98.71294592, 95.28893413,
       62.40074585, 47.76167873, 77.93768326, 57.83496792, 56.32074611,
       20.65919249, 82.26880065, 30.11216113, 94.60231115, 49.79366209,
       85.65668562, 50.85081512, 84.87302406,  1.98862913, 75.31615746,
       61.97009956,  5.19526679, 54.32049402, 34.95326047, 54.29036352,
       16.7335971 ,  3.15827734, 44.72852056, 62.36342275, 88.00199384,
       38.17066947, 96.80128129,  7.88901197, 72.29348533, 26.0618499 ,
       58.8974542 , 57.9317834 , 85.30793168,  4.99057652, 43.89113309,
       41.0145326 , 26.27739759,  4.3069957 , 40.26799685, 81.29181263,
       20.83777262, 60.42501145, 66.49762553, 66.83190387, 10.56515218,
       24.5238824 , 49.77450542, 83.29186992, 55.74770599, 23.38462909,
       94.11404488, 58.727325  ,  1.06543175, 73.958385  , 28.16787242,
       36.00433821, 25.10092885,  7.23122268, 90.16958674, 55.32453645,
       14.3405077 ,  8.50211511, 23.7223383 , 24.96247203, 51.80457809,
       44.59061518, 79.36541244, 23.10711508, 47.88674613, 98.23236023,
       46.80680881, 56.96585876, 15.33714684, 95.73310463, 80.46261467,
       55.71766745, 16.04600571, 28.92524462, 83.35423106,  4.71354655])

In [16]:
float_df = np.random.uniform(1,100, size=1000)

In [22]:
df_exams['language score']= float_df

In [26]:
round(df_exams,0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,64.0
1,female,group C,some college,standard,completed,69,90,88,41.0
2,female,group B,master's degree,standard,none,90,95,93,26.0
3,male,group A,associate's degree,free/reduced,none,47,57,44,78.0
4,male,group C,some college,standard,none,76,78,75,52.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,26.0
996,male,group C,high school,free/reduced,none,62,55,55,57.0
997,female,group C,high school,free/reduced,completed,59,71,65,81.0
998,female,group D,some college,standard,completed,68,78,77,55.0
999,female,group D,some college,free/reduced,none,77,86,86,75.0